In [24]:
# Importing the dependencies
import sys
sys.path.insert(0, '../preprocessing') # adding syspath
import preprocess
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt 
from math import floor
from sklearn import preprocessing

# Tweaking inline plot sizes
plt.rcParams['figure.figsize'] = [15, 6]

In [4]:
proc = preprocess.SequenceHandler('../data/train.csv', size=26)
proc.convert_sequence_to_2D_sample()

Extracting sequences ...
Adjusting sequence length to 26 ...
Sequence data acquired. (Now convert to appropiate dimension)
Generating 2D view of sequence data ...
Sequence samples generated - design matrix (#samples, #time_steps, #features) = (280, 26, 561), class vector (#samples) = (280). (Now sequence 2-dim is accessible) 


In [56]:
x,y = proc.get_sequence(2)

In [113]:
# Number of classes
len(set(y))

6

## Verifying Data Load

In [13]:
# First 2D sequence record
x[0,:,:]
y[0]

'STANDING'

In [7]:
proc.sequence['1']

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0            0.288585          -0.020294          -0.132905         -0.995279   
1            0.278419          -0.016411          -0.123520         -0.998245   
2            0.279653          -0.019467          -0.113462         -0.995380   
3            0.279174          -0.026201          -0.123283         -0.996091   
4            0.276629          -0.016570          -0.115362         -0.998139   
5            0.277199          -0.010098          -0.105137         -0.997335   
6            0.279454          -0.019641          -0.110022         -0.996921   
7            0.277432          -0.030488          -0.125360         -0.996559   
8            0.277293          -0.021751          -0.120751         -0.997328   
9            0.280586          -0.009960          -0.106065         -0.994803   
10           0.276880          -0.012722          -0.103438         -0.994815   
11           0.276228          -0.021441          -0.108202         -0.998246   
12           0.278457          -0.020415          -0.112732         -0.999135   
13           0.277175          -0.014713          -0.106756         -0.999188   
14           0.297946           0.027094          -0.061668         -0.988641   
15           0.279203          -0.023020          -0.122080         -0.996839   
16           0.279038          -0.014800          -0.116849         -0.996941   
17           0.280135          -0.013917          -0.106370         -0.997695   
18           0.277731          -0.018211          -0.109188         -0.997491   
19           0.275568          -0.016980          -0.111429         -0.997811   
20           0.277562          -0.014318          -0.107877         -0.997904   
21           0.277152          -0.017983          -0.106601         -0.997763   
22           0.275676          -0.021264          -0.110801         -0.997862   
23           0.279200          -0.017714          -0.109161         -0.998389   
24           0.281715          -0.011911          -0.102875         -0.998534   
25           0.278993          -0.014531          -0.106596         -0.998060   

    tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0          -0.983111         -0.913526         -0.995112         -0.983185   
1          -0.975300         -0.960322         -0.998807         -0.974914   
2          -0.967187         -0.978944         -0.996520         -0.963668   
3          -0.983403         -0.990675         -0.997099         -0.982750   
4          -0.980817         -0.990482         -0.998321         -0.979672   
5          -0.990487         -0.995420         -0.997627         -0.990218   
6          -0.967186         -0.983118         -0.997003         -0.966097   
7          -0.966728         -0.981585         -0.996485         -0.966313   
8          -0.961245         -0.983672         -0.997596         -0.957236   
9          -0.972758         -0.986244         -0.995405         -0.973663   
10         -0.973077         -0.985357         -0.995509         -0.973948   
11         -0.987214         -0.992727         -0.998251         -0.985997   
12         -0.984680         -0.996274         -0.999077         -0.982937   
13         -0.990526         -0.993365         -0.999211         -0.990687   
14         -0.816699         -0.901907         -0.988958         -0.794280   
15         -0.974848         -0.983386         -0.997094         -0.973332   
16         -0.981866         -0.982577         -0.997220         -0.981620   
17         -0.987516         -0.990407         -0.998014         -0.987954   
18         -0.993222         -0.996128         -0.997903         -0.992711   
19         -0.990522         -0.997621         -0.998205         -0.989470   
20         -0.994311         -0.995952         -0.998365         -0.993604   
21         -0.989957         -0.996586         -0.998291         -0.989669   
22         -0.990091  

Looks good till here!

## CNN Model

In [127]:
class CNN(nn.Module):
    
    def __init__(self, inp_height, inp_width, filter_size, stride, padding, pool_size):
        super(CNN, self).__init__()
        
        # Conv/Max Pool Layer - (1)
        self.convolution_1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=filter_size, stride=stride, padding=padding)
        #self.relu_1 = nn.RelU() # 2D Output -> floor(n-f+1)
        self.max_pool_1 = nn.MaxPool2d(kernel_size=pool_size) # 2D Output -> floor(n-f+1)/2

        # Dropout Layer - (2)
        self.dropout_1 = nn.Dropout(p=0.1)                
        
        # Conv/Max Pool Layer - (3)
        self.convolution_2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=filter_size, stride=stride, padding=padding)
        #self.relu_2 = nn.RelU() # 2D Output -> floor((floor(n-f+1)/2)-f+1)
        self.max_pool_2 = nn.MaxPool2d(kernel_size=pool_size) # 2D Output -> floor((floor(n-f+1)/2)-f+1)/2    

        # Dropout Layer - (4)
        self.dropout_2 = nn.Dropout(p=0.5)                
        
        # Calculating transformed height, width of 2D grid which is to be flattened
        h = int(floor((floor(inp_height-filter_size+1)/2)-filter_size+1)/2)
        w = int(floor((floor(inp_width-filter_size+1)/2)-filter_size+1)/2)

        # Fully Connected Layer - (5)
        #self.fc_1 = nn.Linear(32*h*w, 100)
        self.fc_1 = nn.Linear(64*h*w, 100)
        
        # Fully Connected Layer - (6)
        self.fc_2 = nn.Linear(100, 6)                                        
        
        
    def forward(self, x):
    
        # Conv/Max Forward Computation - (1)
        out = F.relu(self.convolution_1(x))
        print(f'... after 1st conv: {out.size()}')
        out = self.max_pool_1(out)
        print(f'... after 1st pool: {out.size()}')
        
        # Dropout Computation - (2)
        out = self.dropout_1(out)
        print(f'... after 1st dropout: {out.size()}')

        # Conv/Max Forward Computation - (3)
        out = F.relu(self.convolution_2(out))
        print(f'... after 2nd conv: {out.size()}')
        out = self.max_pool_2(out)
        print(f'... after 2nd pool: {out.size()}')

        # Flattening Data
        out = out.view(out.size(0), -1)
        print(f'... after flattening: {out.size()}')
        
        # Dropout Forward Computation - (4)
        out = self.dropout_2(out)
        print(f'... after 2nd dropout: {out.size()}')
                

        # Fully Connected Layers (5), (6)
        out = self.fc_1(out)        
        print(f'... after 1st fc: {out.size()}')
        out = F.softmax(self.fc_2(out))
        print(f'... after 2nd fc: {out.size()}')
        print(out)
        return out

## Preparing Data for Training - Class Indices + Design Matrix Resize

In [142]:
# Label Encoder
yy = np.array(y)
le = preprocessing.LabelEncoder()
yy = le.fit_transform(yy)
yy

array([2, 1, 0, 3, 4, 5, 2, 1, 0, 1, 0, 3, 4, 5, 4, 2, 1, 0, 3, 4, 5, 2,
       1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4,
       5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0,
       3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2,
       1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4,
       5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 4, 5, 4,
       5, 2, 1, 0, 3, 4, 5, 4, 2, 1, 0, 3, 4, 5, 4, 5, 2, 1, 0, 3, 4, 5,
       4, 5, 2, 1, 0, 3, 4, 5, 4, 5, 2, 1, 0, 3, 4, 5, 4, 5, 2, 1, 0, 3,
       4, 5, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 4, 5, 4, 5, 2, 1,
       0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5,
       2, 1, 0, 3, 4, 5, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1,
       0, 3, 4, 5, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0, 3,
       4, 5, 2, 1, 0, 3, 4, 5, 4, 5, 2, 1, 0, 3, 4, 5], dtype=int64)

In [62]:
# One Hot Label Encoder
# enc = preprocessing.OneHotEncoder()
# enc.fit(yy.reshape((len(yy),1)))
# onehotlabels = enc.transform(yy.reshape((len(yy),1))).toarray()
# onehotlabels.shape
# onehotlabels
#z.reshape((len(z),1))

array([[0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [63]:
y

['STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'WALKING_DOWNSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING',
 'WALKING',
 'WALKING_DOWNSTAIRS',
 'WALKING_UPSTAIRS',
 'STANDING',
 'SITTING',
 'LAYING'

In [143]:
xx = x.reshape((x.shape[0], 1, x.shape[1], x.shape[2]))
xx = torch.from_numpy(xx).float()
yy = torch.from_numpy(yy)
#yy = torch.from_numpy(onehotlabels)

# Moving data to GPU
xx,yy = xx.to(device), yy.to(device)

In [144]:
# Initializing model stuff
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = CNN(xx.size()[2],xx.size()[3],5,1,0,2).to(device) # moving model to GPU
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001) #can pass all or part of the model parameters [to optimize only a part of the model]
criterion = nn.CrossEntropyLoss()

## Training Loop

In [187]:
## Finally this THING WORKS!! (need to implement batch + epoch loop)
# Train Step
model.train()
optimizer.zero_grad()

y_ = model.forward(xx[0:3,:,:,:])
loss = criterion(y_, yy[0:3].long())

loss.backward(loss)
optimizer.step()

# Eval Step
# model.eval()
# with torch.no_grad():
#     y_

print(loss)

... after 1st conv: torch.Size([3, 32, 22, 557])
... after 1st pool: torch.Size([3, 32, 11, 278])
... after 1st dropout: torch.Size([3, 32, 11, 278])
... after 2nd conv: torch.Size([3, 64, 7, 274])
... after 2nd pool: torch.Size([3, 64, 3, 137])
... after flattening: torch.Size([3, 26304])
... after 2nd dropout: torch.Size([3, 26304])
... after 1st fc: torch.Size([3, 100])
... after 2nd fc: torch.Size([3, 6])
tensor([[2.3753e-02, 6.8295e-02, 9.0795e-01, 1.1146e-07, 2.8883e-07, 6.4755e-07],
        [2.5948e-02, 8.9633e-01, 7.7725e-02, 1.6671e-07, 3.1296e-07, 3.7656e-07],
        [9.2433e-01, 2.8608e-02, 4.7060e-02, 6.7467e-08, 1.2157e-07, 2.6743e-07]],
       grad_fn=<SoftmaxBackward>)
tensor(1.1155, grad_fn=<NllLossBackward>)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:64: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [81]:
xx.size()

torch.Size([280, 1, 26, 561])

In [189]:
yy.size()

torch.Size([280])